larm=Limb(name='L_arm' )
larm.doGuide()
rarm=Limb(name='R_arm')
rarm.mirrorConnectGuide(larm)

lhand=Hand(name='L_hand', fingerNum=4)
lhand.doGuide()

rhand=Hand(name='R_hand', fingerNum=4)
rhand.mirrorConnectGuide(lhand)

lfoot=Foot(name='L_foot')
lfoot.doGuide()
rfoot=Foot(name='R_foot')
rfoot.mirrorConnectGuide(lfoot)

n=Neck(name='neck', guideDict={'moveall':[0,10,0]})
n.doGuide()

s=Spine(name='spine')
s.doGuide()

lclav=Chain(name='L_clavicle')
lclav.doGuide()
rclav=Chain(name='R_clavicle')
rclav.mirrorConnectGuide(lclav)

lleg=Limb(name='L_leg' )
lleg.doGuide()
rleg=Limb(name='R_leg')
rleg.mirrorConnectGuide(lleg)

llegShoulder=Chain(name='L_legShoulder')
llegShoulder.doGuide()
rlegShoulder=Chain(name='R_legShoulder')
rlegShoulder.mirrorConnectGuide(llegShoulder)
### 
## guide from scene
larm=Limb(name='L_arm' )
larm.getGuideFromScene()
rarm=Limb(name='R_arm')
rarm.getGuideFromScene()

lhand=Hand(name='L_hand', fingerNum=4)
lhand.getGuideFromScene()
rhand=Hand(name='R_hand', fingerNum=4)
rhand.getGuideFromScene()

lfoot=Foot(name='L_foot')
lfoot.getGuideFromScene()
rfoot=Foot(name='R_foot')
rfoot.getGuideFromScene()

n=Neck(name='neck', guideDict={'moveall':[0,10,0]})
n.getGuideFromScene()

s=Spine(name='spine')
s.getGuideFromScene()

lclav=Chain(name='L_clavicle')
lclav.getGuideFromScene()
rclav=Chain(name='R_clavicle')
rclav.getGuideFromScene()

lleg=Limb(name='L_leg' )
lleg.getGuideFromScene()
rleg=Limb(name='R_leg')
rleg.getGuideFromScene()

llegShoulder=Chain(name='L_legShoulder')
llegShoulder.getGuideFromScene()
rlegShoulder=Chain(name='R_legShoulder')
rlegShoulder.getGuideFromScene()

##Rig
s.doRig()
lclav.doRig()
rclav.doRig()
rhand.doRig()
lhand.doRig()
larm.doRig()
rarm.doRig()
rfoot.doRig()
lfoot.doRig()
n.doRig()
lleg.doRig()
rleg.doRig()
llegShoulder.doRig()
rlegShoulder.doRig()

larb= RibbonBezier(name='LarmBezier', size=4.5, offsetStart=0.05, offsetEnd=0.1)
larb.doRig()
larb.connectToLimb(larm)
rarb= RibbonBezier(name='RarmBezier', size=4.5, offsetStart=0.05, offsetEnd=0.1)
rarb.doRig()
rarb.connectToLimb(rarm)

llrb= RibbonBezier(name='LlegBezier', size=6.5, offsetStart=0.05, offsetEnd=0.1)
llrb.doRig()
llrb.connectToLimb(lleg)
rlrb= RibbonBezier(name='RlegBezier', size=6.5 ,offsetStart=0.05, offsetEnd=0.1)
rlrb.doRig()
rlrb.connectToLimb(rleg)

pm.parentConstraint (s.endTipJnt, lclav.moveall, mo=True)
pm.parentConstraint (s.endTipJnt, rclav.moveall, mo=True)
pm.parentConstraint (s.endTipJnt, n.moveall, mo=True)
pm.parentConstraint (rclav.jntList[-1], rarm.moveall, mo=True)
pm.parentConstraint (lclav.jntList[-1], larm.moveall, mo=True)
pm.parentConstraint (larm.lastTipJnt, lhand.moveall, mo=True)
pm.parentConstraint (rarm.lastTipJnt, rhand.moveall, mo=True)
pm.parentConstraint (s.startTipJnt, llegShoulder.moveall, mo=True)
pm.parentConstraint (s.startTipJnt, rlegShoulder.moveall, mo=True)
pm.parentConstraint (rlegShoulder.jntList[-1], rleg.moveall, mo=True)
pm.parentConstraint (llegShoulder.jntList[-1], lleg.moveall, mo=True)
pm.parentConstraint (lfoot.limbConnectionCntrl, lleg.ikCntrl, mo=True)
pm.parentConstraint (rfoot.limbConnectionCntrl, rleg.ikCntrl, mo=True)


pm.parent ( lclav.moveall, s.endTipJnt)
pm.parent ( rclav.moveall, s.endTipJnt)
pm.parent ( n.moveall, s.endTipJnt)
pm.parent ( rarm.moveall,rclav.jntList[-1])
pm.parent ( larm.moveall,lclav.jntList[-1])
pm.parent ( lhand.moveall, larm.lastTipJnt)
pm.parent ( rhand.moveall, rarm.lastTipJnt)
pm.parent ( llegShoulder.moveall, s.startTipJnt)
pm.parent ( rlegShoulder.moveall, s.startTipJnt)
pm.parent ( rleg.moveall, rlegShoulder.jntList[-1])
pm.parent ( lleg.moveall, llegShoulder.jntList[-1])
pm.parent ( lleg.ikCntrl, lfoot.limbConnectionCntrl)
pm.parent (rleg.ikCntrl, rfoot.limbConnectionCntrl)


createSpc (None, 'global')
createSpc (larm.lastJnt, 'lhand')
createSpc (rarm.lastJnt, 'rhand')
createSpc (s.endJnt, 'chest')
createSpc (s.startJnt, 'cog')
createSpc (lleg.lastJnt, 'lfoot')
createSpc (rleg.lastJnt, 'rfoot')
createSpc (lclav.jntList[-1], 'lclav')
createSpc (rclav.jntList[-1], 'rclav')
createSpc (n.startJnt, 'neck')
createSpc (n.endJnt, 'head')

addSpc (target=larm.ikCntrl, spaceList=['global','chest','cog','lclav'], switcher=larm.ikCntrl.getParent(), type='parent')
addSpc (target=rarm.ikCntrl, spaceList=['global','chest','cog','rclav'], switcher=rarm.ikCntrl.getParent(), type='parent')
addSpc (target=larm.poleVec, spaceList=['global','chest','cog','lclav'], switcher=larm.poleVec.getParent(), type='parent')
addSpc (target=rarm.poleVec, spaceList=['global','chest','cog','rclav'], switcher=rarm.poleVec.getParent(), type='parent')
addSpc (target=lleg.poleVec, spaceList=['global','chest','cog'], switcher=lleg.poleVec.getParent(), type='parent')
addSpc (target=rleg.poleVec, spaceList=['global','chest','cog'], switcher=rleg.poleVec.getParent(), type='parent')
addSpc (target=s.endIkCntrl, spaceList=['global','cog'], switcher=s.endIkCntrl.getParent(), type='parent')
